In [79]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [87]:
# Step 1: URL of wikipedia
url = "https://en.wikipedia.org/wiki/List_of_companies_of_India"
# Step 2: Add headers to behave like a real browser
headers = {

    "user-Agent" : "Mozilla/5.0"
}
# Step 3: Send request
response = requests.get(url, headers = headers)
content = response.text

# Step 4: Convert HTML into BeautifulSoup object
soup = BeautifulSoup(content,'html.parser')

# Step 5: Find all company cards

table_heading = soup.find_all("th", rowspan="2")

# extract columns of the table
col_name =[]
for i in table_heading:
    a = i.get_text(strip= True)
    col_name.append(a)

# Extract table rows
table_row = soup.find_all("tr",style="background:#ffffff;")

all_companies = []

for i in table_row:
    table_data = i.find_all("td")
    # Create dictionary using zip
    one_row = {}
    for colname, tablevalue in zip(col_name,table_data):
        one_row[colname] = tablevalue.get_text(strip=True, separator = " ")

# # Extract company link
    linkcol = i.find("a")
    one_row["Go_To"] = f"https://en.wikipedia.org/{linkcol.get("href"," ")}"
    
    all_companies.append(one_row)



df = pd.DataFrame(all_companies)

df = df.rename(columns={"Headquarters" : "HQ City","Founded": "Founded Year","Notes" : "Root Business"})

df.head(20)

df.to_excel(r'C:\Users\hp\Downloads\scraping\List_of_companies.xlsx', sheet_name= 'Details',index= False)

print("File saved successfully!")

,Name,Industry,Sector,HQ City,Founded Year,Root Business,Go_To
0,63 Moons Technologies,Technology,Software,Mumbai,1988,Financial technology,https://en.wikipedia.org//wiki/63_Moons_Techno...
1,Aban Offshore,Energy,Oil & gas offshore drilling & other services,Chennai,1986,"Oil, petrochemical",https://en.wikipedia.org//wiki/Aban_Offshore
2,ABG Shipyard,Industrials,Shipbuilding,Ahmedabad,1985,Ship building,https://en.wikipedia.org//wiki/ABG_Shipyard
3,ABP Group,Consumer services,Broadcasting & entertainment,Kolkata,1922,"Media, news",https://en.wikipedia.org//wiki/ABP_Group
4,ACC,Industrials,Cement,Mumbai,1936,Cement,https://en.wikipedia.org//wiki/ACC_(company)
5,ACG Group,Industrials,Machinery: specialty,Mumbai,1961,Pharmaceutical industry machinery & medicinal ...,https://en.wikipedia.org//wiki/ACG_Group
6,Acko General Insurance,Insurance,Full line insurance,Mumbai,2016,Insurance,https://en.wikipedia.org//wiki/Acko_General_In...
7,Action Construction Equipment,Industrials,Machinery: construction & handling,Faridabad,1995,"Bulldozers, cranes",https://en.wikipedia.org//wiki/Action_Construc...
8,Action Group,Conglomerate,—,New Delhi,1972,"Apparel, chemicals, retail, steel",https://en.wikipedia.org//wiki/Action_Group_(c...
9,Adani Group,Conglomerate,—,Ahmedabad,1988,Conglomerate,https://en.wikipedia.org//wiki/Adani_Group
10,Adani Power,Utilities,Alternative electricity,Mumbai,1910,"Thermal & solar power generation, part of Adan...",https://en.wikipedia.org//wiki/Adani_Power
11,Aditya Birla Fashion and Retail,Retail,Specialty retailers,Mumbai,1997,Clothing retailer,https://en.wikipedia.org//wiki/Aditya_Birla_Fa...
12,Aditya Birla Group,Conglomerate,—,Mumbai,1857,"Agribusiness, cement, chemicals",https://en.wikipedia.org//wiki/Aditya_Birla_Group
13,Ador Group,Conglomerate,—,Mumbai,1977,"Electronics, energy, chemicals",https://en.wikipedia.org//wiki/Ador_Group
14,Afcons Infrastructure,Industrials,Construction,Mumbai,1959,Construction,https://en.wikipedia.org//wiki/Afcons_Infrastr...
15,Air India,Consumer services,Airlines,New Delhi,1932,"Airline, part of Tata Sons",https://en.wikipedia.org//wiki/Air_India
16,Air India Express,Consumer services,Airlines,Kochi,2005,"Low-cost airline, part of Air India",https://en.wikipedia.org//wiki/Air_India_Express
17,Ajanta Group,Conglomerate,—,Ahmedabad,1971,"Textile, transport, construction machinery",https://en.wikipedia.org//wiki/Ajanta_Group
18,Alkem Laboratories,Health care,Pharmaceuticals,Mumbai,1973,Pharma,https://en.wikipedia.org//wiki/Alkem_Laboratories
19,Allcargo Logistics,Industrials,Industrial transportation,Mumbai,1993,Logistics & transportation,https://en.wikipedia.org//wiki/Allcargo_Logistics

In [91]:
df.iloc[0:25]

,Name,Industry,Sector,HQ City,Founded Year,Root Business,Go_To
0,63 Moons Technologies,Technology,Software,Mumbai,1988,Financial technology,https://en.wikipedia.org//wiki/63_Moons_Techno...
1,Aban Offshore,Energy,Oil & gas offshore drilling & other services,Chennai,1986,"Oil, petrochemical",https://en.wikipedia.org//wiki/Aban_Offshore
2,ABG Shipyard,Industrials,Shipbuilding,Ahmedabad,1985,Ship building,https://en.wikipedia.org//wiki/ABG_Shipyard
3,ABP Group,Consumer services,Broadcasting & entertainment,Kolkata,1922,"Media, news",https://en.wikipedia.org//wiki/ABP_Group
4,ACC,Industrials,Cement,Mumbai,1936,Cement,https://en.wikipedia.org//wiki/ACC_(company)
5,ACG Group,Industrials,Machinery: specialty,Mumbai,1961,Pharmaceutical industry machinery & medicinal ...,https://en.wikipedia.org//wiki/ACG_Group
6,Acko General Insurance,Insurance,Full line insurance,Mumbai,2016,Insurance,https://en.wikipedia.org//wiki/Acko_General_In...
7,Action Construction Equipment,Industrials,Machinery: construction & handling,Faridabad,1995,"Bulldozers, cranes",https://en.wikipedia.org//wiki/Action_Construc...
8,Action Group,Conglomerate,—,New Delhi,1972,"Apparel, chemicals, retail, steel",https://en.wikipedia.org//wiki/Action_Group_(c...
9,Adani Group,Conglomerate,—,Ahmedabad,1988,Conglomerate,https://en.wikipedia.org//wiki/Adani_Group
10,Adani Power,Utilities,Alternative electricity,Mumbai,1910,"Thermal & solar power generation, part of Adan...",https://en.wikipedia.org//wiki/Adani_Power
11,Aditya Birla Fashion and Retail,Retail,Specialty retailers,Mumbai,1997,Clothing retailer,https://en.wikipedia.org//wiki/Aditya_Birla_Fa...
12,Aditya Birla Group,Conglomerate,—,Mumbai,1857,"Agribusiness, cement, chemicals",https://en.wikipedia.org//wiki/Aditya_Birla_Group
13,Ador Group,Conglomerate,—,Mumbai,1977,"Electronics, energy, chemicals",https://en.wikipedia.org//wiki/Ador_Group
14,Afcons Infrastructure,Industrials,Construction,Mumbai,1959,Construction,https://en.wikipedia.org//wiki/Afcons_Infrastr...
15,Air India,Consumer services,Airlines,New Delhi,1932,"Airline, part of Tata Sons",https://en.wikipedia.org//wiki/Air_India
16,Air India Express,Consumer services,Airlines,Kochi,2005,"Low-cost airline, part of Air India",https://en.wikipedia.org//wiki/Air_India_Express
17,Ajanta Group,Conglomerate,—,Ahmedabad,1971,"Textile, transport, construction machinery",https://en.wikipedia.org//wiki/Ajanta_Group
18,Alkem Laboratories,Health care,Pharmaceuticals,Mumbai,1973,Pharma,https://en.wikipedia.org//wiki/Alkem_Laboratories
19,Allcargo Logistics,Industrials,Industrial transportation,Mumbai,1993,Logistics & transportation,https://en.wikipedia.org//wiki/Allcargo_Logistics
20,Amartex,Basic materials,Textile products,Gurugram,1984,Textiles,https://en.wikipedia.org//wiki/Amartex
21,Ambuja Cements,Industrials,Cement,Mumbai,1983,Cement,https://en.wikipedia.org//wiki/Ambuja_Cements
22,Amrutanjan Healthcare,Health care,Ayurvedic producers,Chennai,1893,Alternative medicines,https://en.wikipedia.org//wiki/Amrutanjan_Heal...
23,Amul,Consumer goods,Food products,Anand,1946,Dairy,https://en.wikipedia.org//wiki/Amul
24,Angel One,Financials,Investment services,Mumbai,1996,Stock broker,https://en.wikipedia.org//wiki/Angel_One_(comp...

In [93]:
df.loc[20:25]

,Name,Industry,Sector,HQ City,Founded Year,Root Business,Go_To
20,Amartex,Basic materials,Textile products,Gurugram,1984,Textiles,https://en.wikipedia.org//wiki/Amartex
21,Ambuja Cements,Industrials,Cement,Mumbai,1983,Cement,https://en.wikipedia.org//wiki/Ambuja_Cements
22,Amrutanjan Healthcare,Health care,Ayurvedic producers,Chennai,1893,Alternative medicines,https://en.wikipedia.org//wiki/Amrutanjan_Heal...
23,Amul,Consumer goods,Food products,Anand,1946,Dairy,https://en.wikipedia.org//wiki/Amul
24,Angel One,Financials,Investment services,Mumbai,1996,Stock broker,https://en.wikipedia.org//wiki/Angel_One_(comp...
25,Apollo Hospitals,Health care,Health care providers,Chennai,1983,Hospital chain,https://en.wikipedia.org//wiki/Apollo_Hospitals

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369 entries, 0 to 368
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           369 non-null    object
 1   Industry       369 non-null    object
 2   Sector         369 non-null    object
 3   HQ City        369 non-null    object
 4   Founded Year   369 non-null    object
 5   Root Business  369 non-null    object
 6   Go_To          369 non-null    object
dtypes: object(7)
memory usage: 20.3+ KB

In [118]:
# change datatype of Year to number

df['Founded Year'] = pd.to_numeric(df['Founded Year'], errors="coerce").fillna(0).astype(int)

In [119]:
df['Founded Year'].dtypes

dtype('int64')

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369 entries, 0 to 368
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           369 non-null    object
 1   Industry       369 non-null    object
 2   Sector         369 non-null    object
 3   HQ City        369 non-null    object
 4   Founded Year   369 non-null    int64
 5   Root Business  369 non-null    object
 6   Go_To          369 non-null    object
dtypes: int64(1), object(6)
memory usage: 20.3+ KB

In [121]:
year_wise=df.loc[df['Founded Year'] > 1990, ['Name','Industry','Founded Year']]

year_wise.iloc[::5]

,Name,Industry,Founded Year
6,Acko General Insurance,Insurance,2016
24,Angel One,Financials,1996
41,Balaji Telefilms,Consumer services,1994
58,Café Coffee Day,Consumer services,1996
74,Cyient,Technology,1991
84,EaseMyTrip,Consumer services,2008
101,Flipkart,Technology,2007
124,Hero FinCorp,Financials,1991
141,Indiabulls,Financials,2000
148,InMobi,Technology,2007
159,Jio-bp,Energy,2008
169,Jubilant FoodWorks,Consumer services,1995
193,MakeMyTrip,Technology,2000
204,Micromax Informatics,Consumer goods,2000
216,Myntra,Technology,2009
226,Omega Seiki Mobility,Consumer goods,2018
241,PVR INOX,Consumer services,1997
252,Reliance Digital,Retail,2007
261,Swan Defence and Heavy Industries Limited,Industrials,1997
269,Samtel Avionics,Industrials,2005
280,Shree Renuka Sugars,Consumer goods,1998
289,SSS Defence,Industrials,2017
297,Swiggy,Technology,2014
321,Thyrocare,Health care,1996
351,Welspun Corp,Industrials,1995
359,Yepme,Technology,2011
365,Zeta,Technology,2015